"""bc -> bpl translation helpers + the llvm_to_bpl orchestrator.

Extracted from share/smack/top.py during Phase B5 of the modernization plan.
The `llvm_to_bpl` driver chains: `llvm2bpl` subprocess → `annotate_bpl` →
`memsafety_subproperty_selection` → `replace_reach_error` → `transform_bpl`.
"""

import os
import re
import sys
from pathlib import Path

from smack.cli.results import VProperty
from smack.constants import VERSION, inlined_procedures
from smack.pipeline.transform import transform_bpl
from smack.utils import temporary_file, try_command


def procedure_annotation(name, args):
    if name in args.entry_points:
        return "{:entrypoint}"
    elif args.modular and re.match("|".join(inlined_procedures()).replace("$", r"\$"), name):
        return "{:inline 1}"
    elif (not args.modular) and args.verifier == "boogie":
        return f"{{:inline {args.unroll}}}"
    else:
        return ""


def annotate_bpl(args):
    """Annotate the Boogie source file with additional metadata."""

    proc_decl = re.compile(r"procedure\s+([^\s(]*)\s*\(")

    with Path(args.bpl_file).open("r+") as f:
        bpl = f"// generated by SMACK version {VERSION} for {args.verifier}\n"
        bpl += "// via {}\n\n".format(" ".join(sys.argv))
        bpl += proc_decl.sub(
            lambda m: f"procedure {procedure_annotation(m.group(1), args)} {m.group(1)}(",
            f.read(),
        )
        f.seek(0)
        f.truncate()
        f.write(bpl)


def memsafety_subproperty_selection(args):
    if VProperty.MEMORY_SAFETY in args.check:
        return

    selected_props = [p.boogie_attr() for p in VProperty.mem_safe_subprops() if p in args.check]

    def replace_assertion(m):
        if len(selected_props) > 0:
            if m.group(2) and m.group(3) in selected_props:
                attrib = m.group(2)
                expr = m.group(4)
            else:
                attrib = ""
                expr = "true"
            return m.group(1) + attrib + expr + ";"
        else:
            return m.group(0)

    with Path(args.bpl_file).open("r+") as f:
        lines = f.readlines()
        f.seek(0)
        f.truncate()
        for line in lines:
            line = re.sub(r"^(\s*assert\s*)({:(.+)})?(.+);", replace_assertion, line)
            f.write(line)


def replace_reach_error(args):
    """Replaces calls to reach_error in SVCOMP benchmarks with assert false."""

    if args.language != "svcomp":
        return

    if (
        VProperty.MEMORY_SAFETY in args.check
        or VProperty.MEMLEAK in args.check
        or VProperty.INTEGER_OVERFLOW in args.check
    ):
        return

    with Path(args.bpl_file).open() as bf:
        content = bf.read()
    content = content.replace("call reach_error();", "assert false; call reach_error();")
    with Path(args.bpl_file).open("w") as bf:
        bf.write(content)


def _llvm2bpl_cmd(
    args,
    *,
    bpl_file=None,
    ll_file=None,
    memory_partitioner=None,
    memory_partition_oracle=None,
    memory_partition_report=None,
    include_devirt_report=True,
    skip_devirt=False,
):
    cmd = ["llvm2bpl", args.linked_bc_file]
    if bpl_file:
        cmd += ["-bpl", bpl_file]
    cmd += ["-warn-type", args.warn]
    # sea-dsa was replaced by the SVF-Andersen memory partition; its -sea-dsa*
    # flags are gone. The region partition is now produced unconditionally.
    if sys.stdout.isatty():
        cmd += ["-colored-warnings"]
    cmd += ["-source-loc-syms"]
    if args.provenance_syms or getattr(args, "diff_product_mode", None):
        cmd += ["-provenance-syms"]
    for ep in args.entry_points:
        cmd += ["-entry-points", ep]
    for cf in args.checked_functions:
        cmd += ["-checked-functions", cf]
    if args.debug:
        cmd += ["-debug"]
    if args.debug_only:
        cmd += ["-debug-only", args.debug_only]
    if ll_file:
        cmd += ["-ll", ll_file]
    if "impls" in args.mem_mod:
        cmd += ["-mem-mod-impls"]
    if args.static_unroll:
        cmd += ["-static-unroll"]
    if args.integer_encoding == "bit-vector":
        cmd += ["-bit-precise"]
    if args.integer_encoding == "wrapped-integer":
        cmd += ["-wrapped-integer-encoding"]
    if args.timing_annotations:
        cmd += ["-timing-annotations"]
    if args.pointer_encoding == "bit-vector":
        cmd += ["-bit-precise-pointers"]
    if args.no_byte_access_inference:
        cmd += ["-no-byte-access-inference"]
    if args.rewrite_bitwise_ops:
        cmd += ["-rewrite-bitwise-ops"]
    if args.no_memory_splitting:
        cmd += ["-no-memory-splitting"]
    # Memory partitioning is now SVF-Andersen only — the -smack-memory-partitioner
    # selector, its external oracle, and all -smack-svf-* tuning flags were removed
    # with sea-dsa. Devirtualization now runs on SVF's resolved call graph and is
    # ON by default; -smack-skip-devirt turns it off.
    if skip_devirt:
        cmd += ["-smack-skip-devirt"]
    if include_devirt_report and getattr(args, "devirt_report", None):
        cmd += ["-smack-devirt-report", args.devirt_report]
    if memory_partition_report:
        cmd += ["-smack-memory-partition-report", memory_partition_report]
    if args.static_init_zero_memset_threshold is not None:
        cmd += [
            "-static-init-zero-memset-threshold",
            str(args.static_init_zero_memset_threshold),
        ]
    if args.check.contains_mem_safe_props():
        cmd += ["-memory-safety"]
    if VProperty.INTEGER_OVERFLOW in args.check:
        cmd += ["-integer-overflow"]
    if VProperty.RUST_PANICS in args.check:
        cmd += ["-rust-panics"]
    if args.fail_on_loop_exit:
        cmd += ["-fail-on-loop-exit"]
    if args.llvm_assumes:
        cmd += ["-llvm-assumes=" + args.llvm_assumes]
    if args.float:
        cmd += ["-float"]
    if args.modular:
        cmd += ["-modular"]
    return cmd


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _resolve_svf_timeout(args) -> int:
    if getattr(args, "svf_timeout", None) is not None:
        return int(args.svf_timeout)
    return int(os.environ.get("SMACK_SVF_TIMEOUT", "300"))


def _uses_svf_memory_oracle(partitioner: str) -> bool:
    return partitioner == "svf-refined"


def generate_svf_memory_partition_oracle(args) -> str:
    pre_ll = temporary_file("svf-pre-bpl", ".ll", args)
    oracle = temporary_file("svf-memory-partition", ".json", args)
    pre_cmd = _llvm2bpl_cmd(
        args,
        ll_file=pre_ll,
        memory_partitioner="sea-dsa",
        include_devirt_report=False,
        skip_devirt=True,
    )
    try_command(pre_cmd, console=True)

    svf_wpa = getattr(args, "svf_wpa", None) or os.environ.get("SMACK_SVF_WPA") or "wpa"
    svf_extapi = getattr(args, "svf_extapi", None) or os.environ.get("SMACK_SVF_EXTAPI")
    if not svf_extapi:
        sys.exit(
            f"Error: --memory-partitioner {args.memory_partitioner} requires --svf-extapi or "
            "SMACK_SVF_EXTAPI when --memory-partition-oracle is not provided"
        )
    svf_mem_par = (
        getattr(args, "svf_mem_par", None)
        or os.environ.get("SMACK_SVF_MEM_PAR")
        or "intra-disjoint"
    )
    adapter = _repo_root() / "tools" / "svf_memory_partition_adapter.py"
    adapter_cmd = [
        sys.executable,
        str(adapter),
        "--bc",
        pre_ll,
        "--out",
        oracle,
        "--svf-wpa",
        str(svf_wpa),
        "--svf-extapi",
        str(svf_extapi),
        "--mem-par",
        str(svf_mem_par),
        "--timeout",
        str(_resolve_svf_timeout(args)),
    ]
    adapter_cmd += ["--indirect-call-targets"]
    if getattr(args, "svf_loop_diagnostics", False):
        adapter_cmd += ["--loop-diagnostics"]
    if getattr(args, "svf_saber_diagnostics", False):
        adapter_cmd += ["--saber-diagnostics"]
    if getattr(args, "svf_mta_diagnostics", False):
        adapter_cmd += ["--mta-diagnostics"]
    try_command(adapter_cmd, console=True)
    return oracle


def llvm_to_bpl(args):
    """Translate the LLVM bitcode file to a Boogie source file."""

    oracle = getattr(args, "memory_partition_oracle", None)
    if (
        _uses_svf_memory_oracle(args.memory_partitioner)
        and not oracle
        and not args.no_memory_splitting
    ):
        oracle = generate_svf_memory_partition_oracle(args)

    cmd = _llvm2bpl_cmd(
        args,
        bpl_file=args.bpl_file,
        ll_file=args.ll_file,
        memory_partition_oracle=oracle,
        memory_partition_report=args.memory_partition_report,
    )
    try_command(cmd, console=True)
    annotate_bpl(args)
    memsafety_subproperty_selection(args)
    replace_reach_error(args)
    transform_bpl(args)
