##===- projects/smack/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=DSA AssistDS smack

include $(LEVEL)/Makefile.common
