##===- projects/smack/tools/smack/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

TOOLNAME=smack
LINK_COMPONENTS = all
# LLVMLIBS = LLVMTransformUtils.a LLVMipa.a LLVMAnalysis.a LLVMTarget.a LLVMMC.a LLVMObject.a LLVMBitReader.a LLVMCore.a LLVMSupport.a
USEDLIBS = smack.a LLVMDataStructure.a AssistDS.a

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

