##===- projects/smack/lib/smack/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=smack
BUILD_ARCHIVE=1
USEDLIBS = LLVMDataStructure.a AssistDS.a

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
