name: SMACK CI

on: [push, pull_request]

jobs:
  check-regressions:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        travis_env:
          [
            "--exhaustive --folder=c/basic",
            "--exhaustive --folder=c/data",
            "--exhaustive --folder=c/ntdrivers-simplified",
            "--exhaustive --folder=c/ntdrivers",
            "--exhaustive --folder=c/bits",
            "--exhaustive --folder=c/float",
            "--exhaustive --folder=c/locks",
            "--exhaustive --folder=c/contracts",
            "--exhaustive --folder=c/simd",
            "--exhaustive --folder=c/memory-safety",
            "--exhaustive --folder=c/pthread",
            "--exhaustive --folder=c/pthread_extras",
            "--exhaustive --folder=c/strings",
            "--exhaustive --folder=c/special",
            "--exhaustive --folder=rust/array --languages=rust",
            "--exhaustive --folder=rust/basic --languages=rust",
            "--exhaustive --folder=rust/box --languages=rust",
            "--exhaustive --folder=rust/functions --languages=rust",
            "--exhaustive --folder=rust/generics --languages=rust",
            "--exhaustive --folder=rust/loops --languages=rust",
            "--exhaustive --folder=rust/panic --languages=rust",
            "--exhaustive --folder=rust/recursion --languages=rust",
            "--exhaustive --folder=rust/structures --languages=rust",
            "--exhaustive --folder=rust/vector --languages=rust",
            "--exhaustive --folder=rust/cargo/** --languages=cargo --threads=1",
            "--exhaustive --folder=llvm --languages=llvm-ir"
          ]
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        env:
          GITHUB_ACTIONS: true
        run: INSTALL_DEV_DEPENDENCIES=1 INSTALL_RUST=1 ./bin/build.sh

      - name: format checking
        run: |
          ./format/run-clang-format.py -r lib/smack include/smack tools share/smack/include share/smack/lib test examples
          flake8 test/regtest.py share/smack/ --extend-exclude share/smack/svcomp/,share/smack/reach.py

      - name: compile and test
        env:
          TRAVIS_ENV: ${{ matrix.travis_env }}
        run: ./bin/build.sh

  # Shaobo: I had to create a per-branch job because matrix doesn't work. The
  # reason is that `if` expression is evaluated before matrix is expanded.
  # See:
  # https://github.community/t/matrix-cannot-be-used-in-jobs-level-if/17177/2
  build-and-push-docker-master:
    runs-on: ubuntu-20.04
    needs: check-regressions

    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: smackers/smack:stable

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-and-push-docker-develop:
    runs-on: ubuntu-20.04
    needs: check-regressions

    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: smackers/smack:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
